export const CLASSIFICATIONS = [
    "uncertain significance",
    "likely benign",
    "drug response",
    "pathogenic",
    "benign",
    "likely pathogenic"
]

// export const CHROMOSOME_MAPPING = {
//     'Chr 1': 1,
//     'Chr 2': 2,
//     'Chr 3': 3,
//     'Chr 4': 4,
//     'Chr 5': 5,
//     'Chr 6': 6,
//     'Chr 7': 7,
//     'Chr 8': 8,
//     'Chr 9': 9,
//     'Chr 10': 10,
//     'Chr 11': 11,
//     'Chr 12': 12,
//     'Chr 13': 13,
//     'Chr 14': 14,
//     'Chr 15': 15,
//     'Chr 16': 16,
//     'Chr 17': 17,
//     'Chr 18': 18,
//     'Chr 19': 19,
//     'Chr 20': 20,
//     'Chr 21': 21,
//     'Chr 22': 22,
//     'Chr X': 'X',
//     'Chr Y': 'Y',
//     'Chr MT': 'M'
// }

export const CHROMOSOMES = [
    'Chr 1',
    'Chr 2',
    'Chr 3',
    'Chr 4',
    'Chr 5',
    'Chr 6',
    'Chr 7',
    'Chr 8',
    'Chr 9',
    'Chr 10',
    'Chr 11',
    'Chr 12',
    'Chr 13',
    'Chr 14',
    'Chr 15',
    'Chr 16',
    'Chr 17',
    'Chr 18',
    'Chr 19',
    'Chr 20',
    'Chr 21',
    'Chr 22',
    'Chr X',
    'Chr Y',
    'Chr MT'
]